### ISSUE TITLE
[ISSUE] How to keep Details plugin always displayed

### ISSUE THREAD

**Issue by xj999** [eltreum0/eltruism#172]
I just started using Eltruism, and after configuring it, I noticed that the Details plugin automatically hides after leaving combat. I would like to know where this can be configured, as I need it to always be displayed.

**Comment by eltreum0** [comment]
Its not a bug, its an option in addons:

If you have AddOnSkins then go to  ElvUI > AddOnSkins > Embed Settings > Turn off Out of Combat (Hide)

If details is showing up on top of the trade chat, try going to AddOnSkins > Embed Settings and making sure that its hiding the Trade/Loot chat, you can also right click the > arrow in order to toggle the details embed.

If you do not have AddOnSkins then go to Eltruism > Skins > Addons > Details > Embed > Hide out of Combat, you can also change the amount of time it takes for it to hide.

In either AddOnSkins or Eltruism embeds you can also Right Click the Chat Toggle (the Arrow [ > ] on the bottom right) to Toggle the Visibility

A shortcut to disabling the combat hide is /eltruism detailshide
